# Generated by Django 2.2.7 on 2019-11-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatilla',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
